rules:
  # SQL Injection Detection
  - id: express-sql-injection
    patterns:
      - pattern: pool.query($SQL, ...)
      - pattern-not: pool.query($SQL, [...])
      - pattern-not: pool.query("...", [...])
    message: Potential SQL injection vulnerability. Always use parameterized queries with placeholders ($1, $2, etc.)
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      owasp: "A03:2021 - Injection"
      cwe: "CWE-89: SQL Injection"

  # Hardcoded Secrets Detection
  - id: hardcoded-credentials
    pattern-either:
      - pattern: |
          const password = "..."
      - pattern: |
          const apiKey = "..."
      - pattern: |
          const secret = "..."
      - pattern: |
          const token = "..."
      - pattern: |
          password: "..."
      - pattern: |
          apiKey: "..."
    pattern-not: |
      const password = ""
    message: Potential hardcoded secret detected. Use environment variables instead.
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      owasp: "A02:2021 - Cryptographic Failures"
      cwe: "CWE-798: Use of Hard-coded Credentials"

  # Unsafe eval Usage
  - id: unsafe-eval-usage
    pattern-either:
      - pattern: eval(...)
      - pattern: Function(...)
      - pattern: new Function(...)
    message: Avoid using eval() or Function() constructor as they can execute arbitrary code
    languages: [typescript, javascript]
    severity: ERROR
    metadata:
      category: security
      owasp: "A03:2021 - Injection"
      cwe: "CWE-95: Improper Neutralization of Directives in Dynamically Evaluated Code"

  # Missing Security Headers
  - id: express-missing-helmet
    pattern: |
      app.use(...)
    pattern-not: |
      app.use(helmet(...))
    message: Consider using helmet.js for security headers (CSP, X-Frame-Options, etc.)
    languages: [typescript, javascript]
    severity: INFO
    metadata:
      category: security
      owasp: "A05:2021 - Security Misconfiguration"

  # Exposed Error Details
  - id: express-error-exposure
    patterns:
      - pattern: |
          res.json({ ..., error: $ERR, ... })
      - metavariable-pattern:
          metavariable: $ERR
          pattern-either:
            - pattern: error.message
            - pattern: error.stack
            - pattern: $X.message
    message: Avoid exposing detailed error messages in API responses. Use generic messages for production.
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      owasp: "A04:2021 - Insecure Design"
      cwe: "CWE-209: Generation of Error Message Containing Sensitive Information"

  # Unvalidated User Input
  - id: express-unvalidated-params
    patterns:
      - pattern: |
          const { $PARAM } = req.params
      - pattern-not-inside: |
          const { $PARAM } = req.params
          ...
          if (!$PARAM || ...) { ... }
      - pattern-not-inside: |
          const { $PARAM } = req.params
          ...
          parseInt($PARAM)
    message: User input from req.params should be validated before use
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      owasp: "A03:2021 - Injection"
      cwe: "CWE-20: Improper Input Validation"

  # Missing CORS Configuration
  - id: express-missing-cors
    pattern: |
      const app = express()
    pattern-not-inside: |
      const app = express()
      ...
      app.use(cors(...))
    message: CORS is not configured. This may allow unauthorized cross-origin requests.
    languages: [typescript, javascript]
    severity: INFO
    metadata:
      category: security
      owasp: "A05:2021 - Security Misconfiguration"
      cwe: "CWE-942: Permissive Cross-domain Policy with Untrusted Domains"

  # Missing Rate Limiting
  - id: express-missing-rate-limit
    pattern: |
      const app = express()
    pattern-not-inside: |
      const app = express()
      ...
      app.use(rateLimit(...))
    message: Rate limiting is not configured. Consider adding rate limiting to prevent abuse.
    languages: [typescript, javascript]
    severity: INFO
    metadata:
      category: security
      owasp: "A04:2021 - Insecure Design"

  # Weak Random Number Generation
  - id: weak-random
    pattern-either:
      - pattern: Math.random()
    message: Math.random() is not cryptographically secure. Use crypto.randomBytes() for security-sensitive operations.
    languages: [typescript, javascript]
    severity: WARNING
    metadata:
      category: security
      owasp: "A02:2021 - Cryptographic Failures"
      cwe: "CWE-330: Use of Insufficiently Random Values"
